# Generated by Django 6.0.4 on 2026-04-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0003_pessoa_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='celular',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='fone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='fone'),
        ),
    ]
